const fs = require('fs');
const path = 'C:/Users/ziaa/Dropbox/ZA/DEV/PROJECTS/JB_CRM/server/accountingRoutes.ts';

const content = [
"",
"// ==========================================",
"// FINANCIAL PERIODS",
"// ==========================================",
"",
"accountingRouter.get('/accounting/financial-periods', requireAgent, async (req: any, res) => {",
"  try {",
"    const conditions: string[] = [];",
"    const params: any[] = [];",
"    let paramIndex = 1;",
"    if (req.query.year) {",
"      conditions.push(`financial_year = $${paramIndex++}`);",
"      params.push(parseInt(req.query.year));",
"    }",
"    if (req.query.status) {",
"      conditions.push(`status = $${paramIndex++}`);",
"      params.push(req.query.status);",
"    }",
"    const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';",
"    const result = await pool.query(",
"      `SELECT * FROM financial_periods ${where} ORDER BY start_date`,",
"      params",
"    );",
"    res.json(result.rows);",
"  } catch (error) {",
"    console.error('Error fetching financial periods:', error);",
"    res.status(500).json({ error: 'Failed to fetch financial periods' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/financial-periods', requireAgent, async (req: any, res) => {",
"  try {",
"    const { name, start_date, end_date, period_type, financial_year } = req.body;",
"    const result = await pool.query(",
"      `INSERT INTO financial_periods (name, start_date, end_date, period_type, financial_year)",
"       VALUES ($1, $2, $3, $4, $5) RETURNING *`,",
"      [name, start_date, end_date, period_type || 'monthly', financial_year || null]",
"    );",
"    res.status(201).json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error creating financial period:', error);",
"    res.status(500).json({ error: 'Failed to create financial period' });",
"  }",
"});",
"",
"accountingRouter.put('/accounting/financial-periods/:id', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const { sql, values } = buildUpdateQuery('financial_periods', req.body, id);",
"    const result = await pool.query(sql, values);",
"    if (result.rows.length === 0) return res.status(404).json({ error: 'Financial period not found' });",
"    res.json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error updating financial period:', error);",
"    res.status(500).json({ error: 'Failed to update financial period' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/financial-periods/:id/close', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const result = await pool.query(",
"      `UPDATE financial_periods SET status = 'closed', closed_at = NOW(), closed_by_id = $2, updated_at = NOW()",
"       WHERE id = $1 AND status = 'open' RETURNING *`,",
"      [id, req.user?.id || null]",
"    );",
"    if (result.rows.length === 0) return res.status(404).json({ error: 'Period not found or already closed' });",
"    res.json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error closing financial period:', error);",
"    res.status(500).json({ error: 'Failed to close financial period' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/financial-periods/auto-generate', requireAgent, async (req: any, res) => {",
"  try {",
"    const { year, start_month } = req.body;",
"    const startMonth = start_month || 4;",
"    const periods: any[] = [];",
"    const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];",
"    for (let i = 0; i < 12; i++) {",
"      const month = ((startMonth - 1 + i) % 12) + 1;",
"      const yr = month >= startMonth ? year : year + 1;",
"      const startDate = new Date(yr, month - 1, 1);",
"      const endDate = new Date(yr, month, 0);",
"      const name = `${monthNames[month - 1]} ${yr}`;",
"      const result = await pool.query(",
"        `INSERT INTO financial_periods (name, start_date, end_date, period_type, financial_year, status)",
"         VALUES ($1, $2, $3, 'monthly', $4, 'open')",
"         ON CONFLICT DO NOTHING RETURNING *`,",
"        [name, startDate.toISOString(), endDate.toISOString(), year]",
"      );",
"      if (result.rows.length > 0) periods.push(result.rows[0]);",
"    }",
"    res.status(201).json({ message: `Generated ${periods.length} periods for FY ${year}/${year + 1}`, periods });",
"  } catch (error) {",
"    console.error('Error auto-generating periods:', error);",
"    res.status(500).json({ error: 'Failed to auto-generate financial periods' });",
"  }",
"});",
"",
"// ==========================================",
"// JOURNAL ENTRIES",
"// ==========================================",
"",
"accountingRouter.get('/accounting/journal-entries', requireAgent, async (req: any, res) => {",
"  try {",
"    const conditions: string[] = [];",
"    const params: any[] = [];",
"    let paramIndex = 1;",
"    if (req.query.status) {",
"      conditions.push(`je.status = $${paramIndex++}`);",
"      params.push(req.query.status);",
"    }",
"    if (req.query.accountId) {",
"      conditions.push(`je.id IN (SELECT journal_entry_id FROM journal_entry_lines WHERE account_id = $${paramIndex++})`);",
"      params.push(parseInt(req.query.accountId));",
"    }",
"    if (req.query.from) {",
"      conditions.push(`je.entry_date >= $${paramIndex++}`);",
"      params.push(req.query.from);",
"    }",
"    if (req.query.to) {",
"      conditions.push(`je.entry_date <= $${paramIndex++}`);",
"      params.push(req.query.to);",
"    }",
"    const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';",
"    const result = await pool.query(",
"      `SELECT je.*,",
"              COALESCE(json_agg(json_build_object(",
"                'id', jel.id, 'account_id', jel.account_id, 'description', jel.description,",
"                'debit_amount', jel.debit_amount, 'credit_amount', jel.credit_amount,",
"                'tax_rate_id', jel.tax_rate_id, 'tax_amount', jel.tax_amount",
"              )) FILTER (WHERE jel.id IS NOT NULL), '[]') as lines",
"       FROM journal_entries je",
"       LEFT JOIN journal_entry_lines jel ON je.id = jel.journal_entry_id",
"       ${where}",
"       GROUP BY je.id",
"       ORDER BY je.entry_date DESC, je.id DESC`,",
"      params",
"    );",
"    res.json(result.rows);",
"  } catch (error) {",
"    console.error('Error fetching journal entries:', error);",
"    res.status(500).json({ error: 'Failed to fetch journal entries' });",
"  }",
"});",
"",
"accountingRouter.get('/accounting/journal-entries/:id', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const entry = await pool.query('SELECT * FROM journal_entries WHERE id = $1', [id]);",
"    if (entry.rows.length === 0) return res.status(404).json({ error: 'Journal entry not found' });",
"    const lines = await pool.query(",
"      `SELECT jel.*, coa.account_code, coa.account_name",
"       FROM journal_entry_lines jel",
"       LEFT JOIN chart_of_accounts coa ON jel.account_id = coa.id",
"       WHERE jel.journal_entry_id = $1",
"       ORDER BY jel.id`,",
"      [id]",
"    );",
"    res.json({ ...entry.rows[0], lines: lines.rows });",
"  } catch (error) {",
"    console.error('Error fetching journal entry:', error);",
"    res.status(500).json({ error: 'Failed to fetch journal entry' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/journal-entries', requireAgent, async (req: any, res) => {",
"  const client = await pool.connect();",
"  try {",
"    await client.query('BEGIN');",
"    const { entry, lines } = req.body;",
"    const totalDebits = lines.reduce((sum: number, l: any) => sum + (l.debit_amount || 0), 0);",
"    const totalCredits = lines.reduce((sum: number, l: any) => sum + (l.credit_amount || 0), 0);",
"    if (totalDebits !== totalCredits) {",
"      await client.query('ROLLBACK');",
"      return res.status(400).json({ error: `Debits (${totalDebits}) must equal credits (${totalCredits})` });",
"    }",
"    const settings = await client.query('SELECT journal_entry_prefix, journal_entry_next_number FROM business_settings LIMIT 1');",
"    let prefix = 'JE';",
"    let nextNum = 1;",
"    if (settings.rows.length > 0) {",
"      prefix = settings.rows[0].journal_entry_prefix || 'JE';",
"      nextNum = settings.rows[0].journal_entry_next_number || 1;",
"    }",
"    const entryNumber = entry.entry_number || `${prefix}-${String(nextNum).padStart(5, '0')}`;",
"    const entryResult = await client.query(",
"      `INSERT INTO journal_entries (entry_number, entry_date, description, source_type, source_id, financial_period_id, status, notes, created_by_id)",
"       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING *`,",
"      [entryNumber, entry.entry_date, entry.description, entry.source_type || 'manual', entry.source_id || null, entry.financial_period_id || null, entry.status || 'draft', entry.notes || null, req.user?.id || null]",
"    );",
"    const journalEntryId = entryResult.rows[0].id;",
"    const insertedLines: any[] = [];",
"    for (const line of lines) {",
"      const lineResult = await client.query(",
"        `INSERT INTO journal_entry_lines (journal_entry_id, account_id, description, debit_amount, credit_amount, tax_rate_id, tax_amount, property_id, landlord_id, tenant_id)",
"         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING *`,",
"        [journalEntryId, line.account_id, line.description || null, line.debit_amount || 0, line.credit_amount || 0, line.tax_rate_id || null, line.tax_amount || 0, line.property_id || null, line.landlord_id || null, line.tenant_id || null]",
"      );",
"      insertedLines.push(lineResult.rows[0]);",
"    }",
"    if (settings.rows.length > 0) {",
"      await client.query('UPDATE business_settings SET journal_entry_next_number = journal_entry_next_number + 1');",
"    }",
"    await client.query('COMMIT');",
"    res.status(201).json({ ...entryResult.rows[0], lines: insertedLines });",
"  } catch (error) {",
"    await client.query('ROLLBACK');",
"    console.error('Error creating journal entry:', error);",
"    res.status(500).json({ error: 'Failed to create journal entry' });",
"  } finally {",
"    client.release();",
"  }",
"});",
"",
"accountingRouter.post('/accounting/journal-entries/:id/post', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const result = await pool.query(",
"      `UPDATE journal_entries SET status = 'posted', posted_at = NOW(), posted_by_id = $2, updated_at = NOW()",
"       WHERE id = $1 AND status = 'draft' RETURNING *`,",
"      [id, req.user?.id || null]",
"    );",
"    if (result.rows.length === 0) return res.status(404).json({ error: 'Entry not found or not in draft status' });",
"    res.json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error posting journal entry:', error);",
"    res.status(500).json({ error: 'Failed to post journal entry' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/journal-entries/:id/reverse', requireAgent, async (req: any, res) => {",
"  const client = await pool.connect();",
"  try {",
"    await client.query('BEGIN');",
"    const { id } = req.params;",
"    const original = await client.query(\"SELECT * FROM journal_entries WHERE id = $1 AND status = 'posted'\", [id]);",
"    if (original.rows.length === 0) {",
"      await client.query('ROLLBACK');",
"      return res.status(404).json({ error: 'Posted entry not found' });",
"    }",
"    const originalLines = await client.query('SELECT * FROM journal_entry_lines WHERE journal_entry_id = $1', [id]);",
"    const settings = await client.query('SELECT journal_entry_prefix, journal_entry_next_number FROM business_settings LIMIT 1');",
"    let prefix = 'JE';",
"    let nextNum = 1;",
"    if (settings.rows.length > 0) {",
"      prefix = settings.rows[0].journal_entry_prefix || 'JE';",
"      nextNum = settings.rows[0].journal_entry_next_number || 1;",
"    }",
"    const entryNumber = `${prefix}-${String(nextNum).padStart(5, '0')}`;",
"    const reversal = await client.query(",
"      `INSERT INTO journal_entries (entry_number, entry_date, description, source_type, source_id, financial_period_id, status, posted_at, posted_by_id, reversed_entry_id, notes, created_by_id)",
"       VALUES ($1, NOW(), $2, 'manual', NULL, $3, 'posted', NOW(), $4, $5, $6, $4) RETURNING *`,",
"      [entryNumber, `Reversal of ${original.rows[0].entry_number}: ${original.rows[0].description}`, original.rows[0].financial_period_id, req.user?.id || null, id, `Auto-reversal of entry ${original.rows[0].entry_number}`]",
"    );",
"    for (const line of originalLines.rows) {",
"      await client.query(",
"        `INSERT INTO journal_entry_lines (journal_entry_id, account_id, description, debit_amount, credit_amount, tax_rate_id, tax_amount, property_id, landlord_id, tenant_id)",
"         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)`,",
"        [reversal.rows[0].id, line.account_id, line.description, line.credit_amount, line.debit_amount, line.tax_rate_id, line.tax_amount, line.property_id, line.landlord_id, line.tenant_id]",
"      );",
"    }",
"    await client.query(",
"      `UPDATE journal_entries SET status = 'reversed', reversed_entry_id = $2, updated_at = NOW() WHERE id = $1`,",
"      [id, reversal.rows[0].id]",
"    );",
"    if (settings.rows.length > 0) {",
"      await client.query('UPDATE business_settings SET journal_entry_next_number = journal_entry_next_number + 1');",
"    }",
"    await client.query('COMMIT');",
"    res.status(201).json(reversal.rows[0]);",
"  } catch (error) {",
"    await client.query('ROLLBACK');",
"    console.error('Error reversing journal entry:', error);",
"    res.status(500).json({ error: 'Failed to reverse journal entry' });",
"  } finally {",
"    client.release();",
"  }",
"});",
"",
"// ==========================================",
"// GENERAL LEDGER & TRIAL BALANCE",
"// ==========================================",
"",
"accountingRouter.get('/accounting/general-ledger/:accountId', requireAgent, async (req: any, res) => {",
"  try {",
"    const { accountId } = req.params;",
"    const account = await pool.query('SELECT * FROM chart_of_accounts WHERE id = $1', [accountId]);",
"    if (account.rows.length === 0) return res.status(404).json({ error: 'Account not found' });",
"    const conditions: string[] = ['jel.account_id = $1', \"je.status = 'posted'\"];",
"    const params: any[] = [accountId];",
"    let paramIndex = 2;",
"    if (req.query.from) {",
"      conditions.push(`je.entry_date >= $${paramIndex++}`);",
"      params.push(req.query.from);",
"    }",
"    if (req.query.to) {",
"      conditions.push(`je.entry_date <= $${paramIndex++}`);",
"      params.push(req.query.to);",
"    }",
"    const result = await pool.query(",
"      `SELECT jel.*, je.entry_number, je.entry_date, je.description as entry_description, je.source_type",
"       FROM journal_entry_lines jel",
"       JOIN journal_entries je ON jel.journal_entry_id = je.id",
"       WHERE ${conditions.join(' AND ')}",
"       ORDER BY je.entry_date, je.id, jel.id`,",
"      params",
"    );",
"    const openingBalance = account.rows[0].opening_balance || 0;",
"    const normalBalance = account.rows[0].normal_balance;",
"    let runningBalance = openingBalance;",
"    const ledgerLines = result.rows.map((row: any) => {",
"      if (normalBalance === 'debit') {",
"        runningBalance += (row.debit_amount || 0) - (row.credit_amount || 0);",
"      } else {",
"        runningBalance += (row.credit_amount || 0) - (row.debit_amount || 0);",
"      }",
"      return { ...row, running_balance: runningBalance };",
"    });",
"    res.json({ account: account.rows[0], opening_balance: openingBalance, entries: ledgerLines, closing_balance: runningBalance });",
"  } catch (error) {",
"    console.error('Error fetching general ledger:', error);",
"    res.status(500).json({ error: 'Failed to fetch general ledger' });",
"  }",
"});",
"",
"accountingRouter.get('/accounting/trial-balance', requireAgent, async (req: any, res) => {",
"  try {",
"    const dateCondition = req.query.asAt ? `AND je.entry_date <= $1` : '';",
"    const params = req.query.asAt ? [req.query.asAt] : [];",
"    const result = await pool.query(",
"      `SELECT coa.id, coa.account_code, coa.account_name, coa.account_type, coa.normal_balance, coa.opening_balance,",
"              COALESCE(SUM(jel.debit_amount), 0) as total_debits,",
"              COALESCE(SUM(jel.credit_amount), 0) as total_credits",
"       FROM chart_of_accounts coa",
"       LEFT JOIN journal_entry_lines jel ON jel.account_id = coa.id",
"       LEFT JOIN journal_entries je ON jel.journal_entry_id = je.id AND je.status = 'posted' ${dateCondition}",
"       WHERE coa.is_active = true",
"       GROUP BY coa.id",
"       ORDER BY coa.account_code`,",
"      params",
"    );",
"    let totalDebitBalances = 0;",
"    let totalCreditBalances = 0;",
"    const accounts = result.rows.map((row: any) => {",
"      const opening = row.opening_balance || 0;",
"      const debits = parseInt(row.total_debits) || 0;",
"      const credits = parseInt(row.total_credits) || 0;",
"      let balance: number;",
"      if (row.normal_balance === 'debit') {",
"        balance = opening + debits - credits;",
"      } else {",
"        balance = opening + credits - debits;",
"      }",
"      if (balance >= 0 && row.normal_balance === 'debit') {",
"        totalDebitBalances += balance;",
"      } else if (balance >= 0 && row.normal_balance === 'credit') {",
"        totalCreditBalances += balance;",
"      } else if (balance < 0 && row.normal_balance === 'debit') {",
"        totalCreditBalances += Math.abs(balance);",
"      } else {",
"        totalDebitBalances += Math.abs(balance);",
"      }",
"      return { ...row, total_debits: debits, total_credits: credits, balance };",
"    });",
"    res.json({ accounts, total_debit_balances: totalDebitBalances, total_credit_balances: totalCreditBalances });",
"  } catch (error) {",
"    console.error('Error fetching trial balance:', error);",
"    res.status(500).json({ error: 'Failed to fetch trial balance' });",
"  }",
"});",
].join('\n');

fs.appendFileSync(path, content, 'utf8');
console.log('Part 2 appended');
