const fs = require('fs');
const path = 'C:/Users/ziaa/Dropbox/ZA/DEV/PROJECTS/JB_CRM/server/accountingRoutes.ts';

const content = [
"",
"// ==========================================",
"// BUSINESS INVOICES (SALES)",
"// ==========================================",
"",
"accountingRouter.get('/accounting/business-invoices', requireAgent, async (req: any, res) => {",
"  try {",
"    const conditions: string[] = [];",
"    const params: any[] = [];",
"    let paramIndex = 1;",
"    if (req.query.status) {",
"      conditions.push(`status = $${paramIndex++}`);",
"      params.push(req.query.status);",
"    }",
"    if (req.query.customerType) {",
"      conditions.push(`customer_type = $${paramIndex++}`);",
"      params.push(req.query.customerType);",
"    }",
"    if (req.query.customerId) {",
"      conditions.push(`customer_id = $${paramIndex++}`);",
"      params.push(parseInt(req.query.customerId));",
"    }",
"    const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';",
"    const result = await pool.query(",
"      `SELECT * FROM business_invoices ${where} ORDER BY invoice_date DESC`,",
"      params",
"    );",
"    res.json(result.rows);",
"  } catch (error) {",
"    console.error('Error fetching business invoices:', error);",
"    res.status(500).json({ error: 'Failed to fetch business invoices' });",
"  }",
"});",
"",
"accountingRouter.get('/accounting/business-invoices/:id', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const invoice = await pool.query('SELECT * FROM business_invoices WHERE id = $1', [id]);",
"    if (invoice.rows.length === 0) return res.status(404).json({ error: 'Invoice not found' });",
"    const lines = await pool.query(",
"      `SELECT bil.*, coa.account_code, coa.account_name, tr.name as tax_rate_name, tr.rate as tax_rate_value",
"       FROM business_invoice_lines bil",
"       LEFT JOIN chart_of_accounts coa ON bil.account_id = coa.id",
"       LEFT JOIN tax_rates tr ON bil.tax_rate_id = tr.id",
"       WHERE bil.business_invoice_id = $1",
"       ORDER BY bil.sort_order, bil.id`,",
"      [id]",
"    );",
"    res.json({ ...invoice.rows[0], lines: lines.rows });",
"  } catch (error) {",
"    console.error('Error fetching business invoice:', error);",
"    res.status(500).json({ error: 'Failed to fetch business invoice' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/business-invoices', requireAgent, async (req: any, res) => {",
"  const client = await pool.connect();",
"  try {",
"    await client.query('BEGIN');",
"    const { invoice, lines } = req.body;",
"    const settings = await client.query('SELECT sales_invoice_prefix, sales_invoice_next_number FROM business_settings LIMIT 1');",
"    let prefix = 'JBINV';",
"    let nextNum = 1;",
"    if (settings.rows.length > 0) {",
"      prefix = settings.rows[0].sales_invoice_prefix || 'JBINV';",
"      nextNum = settings.rows[0].sales_invoice_next_number || 1;",
"    }",
"    const invoiceNumber = invoice.invoice_number || `${prefix}-${String(nextNum).padStart(5, '0')}`;",
"    const subtotal = lines.reduce((sum: number, l: any) => sum + (l.line_total || 0), 0);",
"    const vatAmount = lines.reduce((sum: number, l: any) => sum + (l.tax_amount || 0), 0);",
"    const totalAmount = subtotal + vatAmount;",
"    const invoiceResult = await client.query(",
"      `INSERT INTO business_invoices (invoice_number, invoice_date, due_date, customer_type, customer_id, customer_name, customer_email, customer_address, customer_vat_number, subtotal, vat_amount, total_amount, status, property_id, notes, internal_notes, created_by_id)",
"       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17) RETURNING *`,",
"      [invoiceNumber, invoice.invoice_date, invoice.due_date, invoice.customer_type || null, invoice.customer_id || null, invoice.customer_name, invoice.customer_email || null, invoice.customer_address || null, invoice.customer_vat_number || null, subtotal, vatAmount, totalAmount, invoice.status || 'draft', invoice.property_id || null, invoice.notes || null, invoice.internal_notes || null, req.user?.id || null]",
"    );",
"    const invoiceId = invoiceResult.rows[0].id;",
"    const insertedLines: any[] = [];",
"    for (let i = 0; i < lines.length; i++) {",
"      const line = lines[i];",
"      const lineResult = await client.query(",
"        `INSERT INTO business_invoice_lines (business_invoice_id, description, quantity, unit_price, line_total, tax_rate_id, tax_amount, account_id, sort_order)",
"         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING *`,",
"        [invoiceId, line.description, line.quantity || 1, line.unit_price, line.line_total, line.tax_rate_id || null, line.tax_amount || 0, line.account_id || null, line.sort_order || i]",
"      );",
"      insertedLines.push(lineResult.rows[0]);",
"    }",
"    if (settings.rows.length > 0) {",
"      await client.query('UPDATE business_settings SET sales_invoice_next_number = sales_invoice_next_number + 1');",
"    }",
"    await client.query('COMMIT');",
"    res.status(201).json({ ...invoiceResult.rows[0], lines: insertedLines });",
"  } catch (error) {",
"    await client.query('ROLLBACK');",
"    console.error('Error creating business invoice:', error);",
"    res.status(500).json({ error: 'Failed to create business invoice' });",
"  } finally {",
"    client.release();",
"  }",
"});",
"",
"accountingRouter.put('/accounting/business-invoices/:id', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const check = await pool.query('SELECT status FROM business_invoices WHERE id = $1', [id]);",
"    if (check.rows.length === 0) return res.status(404).json({ error: 'Invoice not found' });",
"    if (check.rows[0].status !== 'draft') return res.status(400).json({ error: 'Only draft invoices can be edited' });",
"    const { sql, values } = buildUpdateQuery('business_invoices', req.body, id);",
"    const result = await pool.query(sql, values);",
"    res.json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error updating business invoice:', error);",
"    res.status(500).json({ error: 'Failed to update business invoice' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/business-invoices/:id/send', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const result = await pool.query(",
"      `UPDATE business_invoices SET status = 'sent', sent_at = NOW(), updated_at = NOW()",
"       WHERE id = $1 AND status = 'draft' RETURNING *`,",
"      [id]",
"    );",
"    if (result.rows.length === 0) return res.status(404).json({ error: 'Draft invoice not found' });",
"    res.json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error sending business invoice:', error);",
"    res.status(500).json({ error: 'Failed to send business invoice' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/business-invoices/:id/void', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const result = await pool.query(",
"      `UPDATE business_invoices SET status = 'void', voided_at = NOW(), updated_at = NOW()",
"       WHERE id = $1 AND status NOT IN ('void', 'paid') RETURNING *`,",
"      [id]",
"    );",
"    if (result.rows.length === 0) return res.status(404).json({ error: 'Invoice not found or cannot be voided' });",
"    res.json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error voiding business invoice:', error);",
"    res.status(500).json({ error: 'Failed to void business invoice' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/business-invoices/:id/record-payment', requireAgent, async (req: any, res) => {",
"  const client = await pool.connect();",
"  try {",
"    await client.query('BEGIN');",
"    const { id } = req.params;",
"    const { amount, payment_method, payment_reference, payment_date } = req.body;",
"    const invoice = await client.query('SELECT * FROM business_invoices WHERE id = $1', [id]);",
"    if (invoice.rows.length === 0) {",
"      await client.query('ROLLBACK');",
"      return res.status(404).json({ error: 'Invoice not found' });",
"    }",
"    const inv = invoice.rows[0];",
"    const newAmountPaid = (inv.amount_paid || 0) + amount;",
"    const newStatus = newAmountPaid >= inv.total_amount ? 'paid' : 'partially_paid';",
"    await client.query(",
"      `UPDATE business_invoices SET amount_paid = $2, status = $3, paid_at = CASE WHEN $3 = 'paid' THEN NOW() ELSE paid_at END, updated_at = NOW() WHERE id = $1`,",
"      [id, newAmountPaid, newStatus]",
"    );",
"    const allocation = await client.query(",
"      `INSERT INTO payment_allocations (payment_date, amount, payment_method, payment_reference, allocation_type, allocation_id, notes, created_by_id)",
"       VALUES ($1, $2, $3, $4, 'sales_invoice', $5, $6, $7) RETURNING *`,",
"      [payment_date || new Date().toISOString(), amount, payment_method || null, payment_reference || null, id, req.body.notes || null, req.user?.id || null]",
"    );",
"    await client.query('COMMIT');",
"    const updated = await pool.query('SELECT * FROM business_invoices WHERE id = $1', [id]);",
"    res.json({ invoice: updated.rows[0], payment: allocation.rows[0] });",
"  } catch (error) {",
"    await client.query('ROLLBACK');",
"    console.error('Error recording payment:', error);",
"    res.status(500).json({ error: 'Failed to record payment' });",
"  } finally {",
"    client.release();",
"  }",
"});",
"",
"// ==========================================",
"// PURCHASE INVOICES",
"// ==========================================",
"",
"accountingRouter.get('/accounting/purchase-invoices', requireAgent, async (req: any, res) => {",
"  try {",
"    const conditions: string[] = [];",
"    const params: any[] = [];",
"    let paramIndex = 1;",
"    if (req.query.status) {",
"      conditions.push(`status = $${paramIndex++}`);",
"      params.push(req.query.status);",
"    }",
"    if (req.query.supplierType) {",
"      conditions.push(`supplier_type = $${paramIndex++}`);",
"      params.push(req.query.supplierType);",
"    }",
"    if (req.query.supplierId) {",
"      conditions.push(`supplier_id = $${paramIndex++}`);",
"      params.push(parseInt(req.query.supplierId));",
"    }",
"    const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';",
"    const result = await pool.query(",
"      `SELECT * FROM purchase_invoices ${where} ORDER BY invoice_date DESC`,",
"      params",
"    );",
"    res.json(result.rows);",
"  } catch (error) {",
"    console.error('Error fetching purchase invoices:', error);",
"    res.status(500).json({ error: 'Failed to fetch purchase invoices' });",
"  }",
"});",
"",
"accountingRouter.get('/accounting/purchase-invoices/:id', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const invoice = await pool.query('SELECT * FROM purchase_invoices WHERE id = $1', [id]);",
"    if (invoice.rows.length === 0) return res.status(404).json({ error: 'Purchase invoice not found' });",
"    const lines = await pool.query(",
"      `SELECT pil.*, coa.account_code, coa.account_name, tr.name as tax_rate_name, tr.rate as tax_rate_value",
"       FROM purchase_invoice_lines pil",
"       LEFT JOIN chart_of_accounts coa ON pil.account_id = coa.id",
"       LEFT JOIN tax_rates tr ON pil.tax_rate_id = tr.id",
"       WHERE pil.purchase_invoice_id = $1",
"       ORDER BY pil.sort_order, pil.id`,",
"      [id]",
"    );",
"    res.json({ ...invoice.rows[0], lines: lines.rows });",
"  } catch (error) {",
"    console.error('Error fetching purchase invoice:', error);",
"    res.status(500).json({ error: 'Failed to fetch purchase invoice' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/purchase-invoices', requireAgent, async (req: any, res) => {",
"  const client = await pool.connect();",
"  try {",
"    await client.query('BEGIN');",
"    const { invoice, lines } = req.body;",
"    const settings = await client.query('SELECT purchase_invoice_prefix, purchase_invoice_next_number FROM business_settings LIMIT 1');",
"    let prefix = 'JBPI';",
"    let nextNum = 1;",
"    if (settings.rows.length > 0) {",
"      prefix = settings.rows[0].purchase_invoice_prefix || 'JBPI';",
"      nextNum = settings.rows[0].purchase_invoice_next_number || 1;",
"    }",
"    const invoiceNumber = invoice.invoice_number || `${prefix}-${String(nextNum).padStart(5, '0')}`;",
"    const subtotal = lines.reduce((sum: number, l: any) => sum + (l.line_total || 0), 0);",
"    const vatAmount = lines.reduce((sum: number, l: any) => sum + (l.tax_amount || 0), 0);",
"    const totalAmount = subtotal + vatAmount;",
"    const invoiceResult = await client.query(",
"      `INSERT INTO purchase_invoices (invoice_number, supplier_type, supplier_id, supplier_name, supplier_email, supplier_address, supplier_vat_number, invoice_date, due_date, subtotal, vat_amount, total_amount, status, property_id, landlord_id, is_rechargeable, notes, created_by_id)",
"       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18) RETURNING *`,",
"      [invoiceNumber, invoice.supplier_type || null, invoice.supplier_id || null, invoice.supplier_name, invoice.supplier_email || null, invoice.supplier_address || null, invoice.supplier_vat_number || null, invoice.invoice_date, invoice.due_date, subtotal, vatAmount, totalAmount, invoice.status || 'draft', invoice.property_id || null, invoice.landlord_id || null, invoice.is_rechargeable || false, invoice.notes || null, req.user?.id || null]",
"    );",
"    const invoiceId = invoiceResult.rows[0].id;",
"    const insertedLines: any[] = [];",
"    for (let i = 0; i < lines.length; i++) {",
"      const line = lines[i];",
"      const lineResult = await client.query(",
"        `INSERT INTO purchase_invoice_lines (purchase_invoice_id, description, quantity, unit_price, line_total, tax_rate_id, tax_amount, account_id, sort_order)",
"         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING *`,",
"        [invoiceId, line.description, line.quantity || 1, line.unit_price, line.line_total, line.tax_rate_id || null, line.tax_amount || 0, line.account_id || null, line.sort_order || i]",
"      );",
"      insertedLines.push(lineResult.rows[0]);",
"    }",
"    if (settings.rows.length > 0) {",
"      await client.query('UPDATE business_settings SET purchase_invoice_next_number = purchase_invoice_next_number + 1');",
"    }",
"    await client.query('COMMIT');",
"    res.status(201).json({ ...invoiceResult.rows[0], lines: insertedLines });",
"  } catch (error) {",
"    await client.query('ROLLBACK');",
"    console.error('Error creating purchase invoice:', error);",
"    res.status(500).json({ error: 'Failed to create purchase invoice' });",
"  } finally {",
"    client.release();",
"  }",
"});",
"",
"accountingRouter.put('/accounting/purchase-invoices/:id', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const check = await pool.query('SELECT status FROM purchase_invoices WHERE id = $1', [id]);",
"    if (check.rows.length === 0) return res.status(404).json({ error: 'Purchase invoice not found' });",
"    if (check.rows[0].status !== 'draft') return res.status(400).json({ error: 'Only draft invoices can be edited' });",
"    const { sql, values } = buildUpdateQuery('purchase_invoices', req.body, id);",
"    const result = await pool.query(sql, values);",
"    res.json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error updating purchase invoice:', error);",
"    res.status(500).json({ error: 'Failed to update purchase invoice' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/purchase-invoices/:id/approve', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const result = await pool.query(",
"      `UPDATE purchase_invoices SET status = 'approved', approved_by_id = $2, approved_at = NOW(), updated_at = NOW()",
"       WHERE id = $1 AND status IN ('draft', 'awaiting_approval') RETURNING *`,",
"      [id, req.user?.id || null]",
"    );",
"    if (result.rows.length === 0) return res.status(404).json({ error: 'Invoice not found or already approved' });",
"    res.json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error approving purchase invoice:', error);",
"    res.status(500).json({ error: 'Failed to approve purchase invoice' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/purchase-invoices/:id/record-payment', requireAgent, async (req: any, res) => {",
"  const client = await pool.connect();",
"  try {",
"    await client.query('BEGIN');",
"    const { id } = req.params;",
"    const { amount, payment_method, payment_reference, payment_date } = req.body;",
"    const invoice = await client.query('SELECT * FROM purchase_invoices WHERE id = $1', [id]);",
"    if (invoice.rows.length === 0) {",
"      await client.query('ROLLBACK');",
"      return res.status(404).json({ error: 'Purchase invoice not found' });",
"    }",
"    const inv = invoice.rows[0];",
"    const newAmountPaid = (inv.amount_paid || 0) + amount;",
"    const newStatus = newAmountPaid >= inv.total_amount ? 'paid' : 'partially_paid';",
"    await client.query(",
"      `UPDATE purchase_invoices SET amount_paid = $2, status = $3, paid_at = CASE WHEN $3 = 'paid' THEN NOW() ELSE paid_at END, updated_at = NOW() WHERE id = $1`,",
"      [id, newAmountPaid, newStatus]",
"    );",
"    const allocation = await client.query(",
"      `INSERT INTO payment_allocations (payment_date, amount, payment_method, payment_reference, allocation_type, allocation_id, notes, created_by_id)",
"       VALUES ($1, $2, $3, $4, 'purchase_invoice', $5, $6, $7) RETURNING *`,",
"      [payment_date || new Date().toISOString(), amount, payment_method || null, payment_reference || null, id, req.body.notes || null, req.user?.id || null]",
"    );",
"    await client.query('COMMIT');",
"    const updated = await pool.query('SELECT * FROM purchase_invoices WHERE id = $1', [id]);",
"    res.json({ invoice: updated.rows[0], payment: allocation.rows[0] });",
"  } catch (error) {",
"    await client.query('ROLLBACK');",
"    console.error('Error recording purchase payment:', error);",
"    res.status(500).json({ error: 'Failed to record payment' });",
"  } finally {",
"    client.release();",
"  }",
"});",
].join('\n');

fs.appendFileSync(path, content, 'utf8');
console.log('Part 3 appended');
