const fs = require('fs');
const path = 'C:/Users/ziaa/Dropbox/ZA/DEV/PROJECTS/JB_CRM/server/accountingRoutes.ts';

const content = [
"",
"// ==========================================",
"// VAT RETURNS",
"// ==========================================",
"",
"accountingRouter.get('/accounting/vat-returns', requireAgent, async (req: any, res) => {",
"  try {",
"    const result = await pool.query('SELECT * FROM vat_returns ORDER BY period_start DESC');",
"    res.json(result.rows);",
"  } catch (error) {",
"    console.error('Error fetching VAT returns:', error);",
"    res.status(500).json({ error: 'Failed to fetch VAT returns' });",
"  }",
"});",
"",
"accountingRouter.get('/accounting/vat-returns/:id', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const vr = await pool.query('SELECT * FROM vat_returns WHERE id = $1', [id]);",
"    if (vr.rows.length === 0) return res.status(404).json({ error: 'VAT return not found' });",
"    const transactions = await pool.query(",
"      `SELECT vrt.*, jel.description as line_description, jel.debit_amount, jel.credit_amount,",
"              je.entry_number, je.entry_date, je.description as entry_description,",
"              coa.account_code, coa.account_name",
"       FROM vat_return_transactions vrt",
"       JOIN journal_entry_lines jel ON vrt.journal_entry_line_id = jel.id",
"       JOIN journal_entries je ON jel.journal_entry_id = je.id",
"       JOIN chart_of_accounts coa ON jel.account_id = coa.id",
"       WHERE vrt.vat_return_id = $1",
"       ORDER BY je.entry_date, vrt.box_number`,",
"      [id]",
"    );",
"    res.json({ ...vr.rows[0], transactions: transactions.rows });",
"  } catch (error) {",
"    console.error('Error fetching VAT return:', error);",
"    res.status(500).json({ error: 'Failed to fetch VAT return' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/vat-returns', requireAgent, async (req: any, res) => {",
"  try {",
"    const { period_start, period_end, notes } = req.body;",
"    const result = await pool.query(",
"      `INSERT INTO vat_returns (period_start, period_end, notes)",
"       VALUES ($1, $2, $3) RETURNING *`,",
"      [period_start, period_end, notes || null]",
"    );",
"    res.status(201).json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error creating VAT return:', error);",
"    res.status(500).json({ error: 'Failed to create VAT return' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/vat-returns/:id/calculate', requireAgent, async (req: any, res) => {",
"  const client = await pool.connect();",
"  try {",
"    await client.query('BEGIN');",
"    const { id } = req.params;",
"    const vr = await client.query('SELECT * FROM vat_returns WHERE id = $1', [id]);",
"    if (vr.rows.length === 0) {",
"      await client.query('ROLLBACK');",
"      return res.status(404).json({ error: 'VAT return not found' });",
"    }",
"    const periodStart = vr.rows[0].period_start;",
"    const periodEnd = vr.rows[0].period_end;",
"    // Clear existing transactions",
"    await client.query('DELETE FROM vat_return_transactions WHERE vat_return_id = $1', [id]);",
"    // Box 1: VAT due on sales (output VAT)",
"    const salesVat = await client.query(",
"      `SELECT COALESCE(SUM(jel.tax_amount), 0) as total",
"       FROM journal_entry_lines jel",
"       JOIN journal_entries je ON jel.journal_entry_id = je.id",
"       WHERE je.status = 'posted' AND je.entry_date >= $1 AND je.entry_date <= $2",
"       AND je.source_type IN ('sales_invoice', 'manual')",
"       AND jel.tax_amount > 0 AND jel.credit_amount > 0`,",
"      [periodStart, periodEnd]",
"    );",
"    const box1 = parseInt(salesVat.rows[0].total) || 0;",
"    // Box 2: VAT due on acquisitions (EU - typically 0 post-Brexit)",
"    const box2 = 0;",
"    // Box 3: Total VAT due",
"    const box3 = box1 + box2;",
"    // Box 4: VAT reclaimed on purchases (input VAT)",
"    const purchaseVat = await client.query(",
"      `SELECT COALESCE(SUM(jel.tax_amount), 0) as total",
"       FROM journal_entry_lines jel",
"       JOIN journal_entries je ON jel.journal_entry_id = je.id",
"       WHERE je.status = 'posted' AND je.entry_date >= $1 AND je.entry_date <= $2",
"       AND je.source_type IN ('purchase_invoice', 'manual')",
"       AND jel.tax_amount > 0 AND jel.debit_amount > 0`,",
"      [periodStart, periodEnd]",
"    );",
"    const box4 = parseInt(purchaseVat.rows[0].total) || 0;",
"    // Box 5: Net VAT due (or reclaimable)",
"    const box5 = Math.abs(box3 - box4);",
"    // Box 6: Total sales excluding VAT",
"    const salesExVat = await client.query(",
"      `SELECT COALESCE(SUM(bi.subtotal), 0) as total",
"       FROM business_invoices bi",
"       WHERE bi.invoice_date >= $1 AND bi.invoice_date <= $2 AND bi.status != 'void'`,",
"      [periodStart, periodEnd]",
"    );",
"    const box6 = parseInt(salesExVat.rows[0].total) || 0;",
"    // Box 7: Total purchases excluding VAT",
"    const purchasesExVat = await client.query(",
"      `SELECT COALESCE(SUM(pi.subtotal), 0) as total",
"       FROM purchase_invoices pi",
"       WHERE pi.invoice_date >= $1 AND pi.invoice_date <= $2 AND pi.status != 'void'`,",
"      [periodStart, periodEnd]",
"    );",
"    const box7 = parseInt(purchasesExVat.rows[0].total) || 0;",
"    // Box 8 & 9: EU supplies (typically 0 post-Brexit)",
"    const box8 = 0;",
"    const box9 = 0;",
"    // Update the VAT return",
"    const updated = await client.query(",
"      `UPDATE vat_returns SET",
"       box1_vat_due_sales = $2, box2_vat_due_acquisitions = $3, box3_total_vat_due = $4,",
"       box4_vat_reclaimed_input = $5, box5_net_vat_due = $6, box6_total_sales_ex_vat = $7,",
"       box7_total_purchases_ex_vat = $8, box8_total_supplies_ex_vat = $9, box9_total_acquisitions_ex_vat = $10,",
"       status = 'calculated', updated_at = NOW()",
"       WHERE id = $1 RETURNING *`,",
"      [id, box1, box2, box3, box4, box5, box6, box7, box8, box9]",
"    );",
"    await client.query('COMMIT');",
"    res.json(updated.rows[0]);",
"  } catch (error) {",
"    await client.query('ROLLBACK');",
"    console.error('Error calculating VAT return:', error);",
"    res.status(500).json({ error: 'Failed to calculate VAT return' });",
"  } finally {",
"    client.release();",
"  }",
"});",
"",
"accountingRouter.post('/accounting/vat-returns/:id/submit', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const result = await pool.query(",
"      `UPDATE vat_returns SET status = 'submitted', submitted_at = NOW(), submitted_by_id = $2, updated_at = NOW()",
"       WHERE id = $1 AND status = 'calculated' RETURNING *`,",
"      [id, req.user?.id || null]",
"    );",
"    if (result.rows.length === 0) return res.status(404).json({ error: 'Calculated VAT return not found' });",
"    res.json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error submitting VAT return:', error);",
"    res.status(500).json({ error: 'Failed to submit VAT return' });",
"  }",
"});",
"",
"accountingRouter.get('/accounting/vat-returns/:id/transactions', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const vr = await pool.query('SELECT * FROM vat_returns WHERE id = $1', [id]);",
"    if (vr.rows.length === 0) return res.status(404).json({ error: 'VAT return not found' });",
"    const periodStart = vr.rows[0].period_start;",
"    const periodEnd = vr.rows[0].period_end;",
"    // Get all posted journal entries with tax in the period",
"    const result = await pool.query(",
"      `SELECT je.id, je.entry_number, je.entry_date, je.description, je.source_type,",
"              jel.id as line_id, jel.debit_amount, jel.credit_amount, jel.tax_amount,",
"              coa.account_code, coa.account_name,",
"              tr.name as tax_rate_name, tr.rate as tax_rate_value",
"       FROM journal_entries je",
"       JOIN journal_entry_lines jel ON je.id = jel.journal_entry_id",
"       JOIN chart_of_accounts coa ON jel.account_id = coa.id",
"       LEFT JOIN tax_rates tr ON jel.tax_rate_id = tr.id",
"       WHERE je.status = 'posted' AND je.entry_date >= $1 AND je.entry_date <= $2",
"       AND jel.tax_amount > 0",
"       ORDER BY je.entry_date, je.id`,",
"      [periodStart, periodEnd]",
"    );",
"    res.json(result.rows);",
"  } catch (error) {",
"    console.error('Error fetching VAT return transactions:', error);",
"    res.status(500).json({ error: 'Failed to fetch VAT return transactions' });",
"  }",
"});",
"",
"// ==========================================",
"// REPORTS",
"// ==========================================",
"",
"accountingRouter.get('/accounting/reports/profit-and-loss', requireAgent, async (req: any, res) => {",
"  try {",
"    const { from, to } = req.query;",
"    if (!from || !to) return res.status(400).json({ error: 'from and to dates are required' });",
"    // Revenue accounts",
"    const revenue = await pool.query(",
"      `SELECT coa.id, coa.account_code, coa.account_name,",
"              COALESCE(SUM(jel.credit_amount), 0) - COALESCE(SUM(jel.debit_amount), 0) as balance",
"       FROM chart_of_accounts coa",
"       LEFT JOIN journal_entry_lines jel ON jel.account_id = coa.id",
"       LEFT JOIN journal_entries je ON jel.journal_entry_id = je.id AND je.status = 'posted' AND je.entry_date >= $1 AND je.entry_date <= $2",
"       WHERE coa.account_type = 'revenue' AND coa.is_active = true",
"       GROUP BY coa.id ORDER BY coa.account_code`,",
"      [from, to]",
"    );",
"    // Expense accounts",
"    const expenses = await pool.query(",
"      `SELECT coa.id, coa.account_code, coa.account_name,",
"              COALESCE(SUM(jel.debit_amount), 0) - COALESCE(SUM(jel.credit_amount), 0) as balance",
"       FROM chart_of_accounts coa",
"       LEFT JOIN journal_entry_lines jel ON jel.account_id = coa.id",
"       LEFT JOIN journal_entries je ON jel.journal_entry_id = je.id AND je.status = 'posted' AND je.entry_date >= $1 AND je.entry_date <= $2",
"       WHERE coa.account_type = 'expense' AND coa.is_active = true",
"       GROUP BY coa.id ORDER BY coa.account_code`,",
"      [from, to]",
"    );",
"    const totalRevenue = revenue.rows.reduce((sum: number, r: any) => sum + (parseInt(r.balance) || 0), 0);",
"    const totalExpenses = expenses.rows.reduce((sum: number, r: any) => sum + (parseInt(r.balance) || 0), 0);",
"    const netProfit = totalRevenue - totalExpenses;",
"    res.json({",
"      period: { from, to },",
"      revenue: revenue.rows.map((r: any) => ({ ...r, balance: parseInt(r.balance) || 0 })),",
"      expenses: expenses.rows.map((r: any) => ({ ...r, balance: parseInt(r.balance) || 0 })),",
"      total_revenue: totalRevenue,",
"      total_expenses: totalExpenses,",
"      net_profit: netProfit",
"    });",
"  } catch (error) {",
"    console.error('Error generating P&L report:', error);",
"    res.status(500).json({ error: 'Failed to generate P&L report' });",
"  }",
"});",
"",
"accountingRouter.get('/accounting/reports/balance-sheet', requireAgent, async (req: any, res) => {",
"  try {",
"    const asAt = req.query.asAt || new Date().toISOString();",
"    const dateCondition = 'AND je.entry_date <= $1';",
"    const fetchAccounts = async (type: string) => {",
"      const isDebitNormal = (type === 'asset' || type === 'expense');",
"      const balanceExpr = isDebitNormal",
"        ? 'COALESCE(SUM(jel.debit_amount), 0) - COALESCE(SUM(jel.credit_amount), 0)'",
"        : 'COALESCE(SUM(jel.credit_amount), 0) - COALESCE(SUM(jel.debit_amount), 0)';",
"      const result = await pool.query(",
"        `SELECT coa.id, coa.account_code, coa.account_name,",
"                COALESCE(coa.opening_balance, 0) + (${balanceExpr}) as balance",
"         FROM chart_of_accounts coa",
"         LEFT JOIN journal_entry_lines jel ON jel.account_id = coa.id",
"         LEFT JOIN journal_entries je ON jel.journal_entry_id = je.id AND je.status = 'posted' ${dateCondition}",
"         WHERE coa.account_type = $2 AND coa.is_active = true",
"         GROUP BY coa.id ORDER BY coa.account_code`,",
"        [asAt, type]",
"      );",
"      return result.rows.map((r: any) => ({ ...r, balance: parseInt(r.balance) || 0 }));",
"    };",
"    const assets = await fetchAccounts('asset');",
"    const liabilities = await fetchAccounts('liability');",
"    const equity = await fetchAccounts('equity');",
"    const totalAssets = assets.reduce((sum: number, a: any) => sum + a.balance, 0);",
"    const totalLiabilities = liabilities.reduce((sum: number, a: any) => sum + a.balance, 0);",
"    const totalEquity = equity.reduce((sum: number, a: any) => sum + a.balance, 0);",
"    res.json({",
"      as_at: asAt,",
"      assets, liabilities, equity,",
"      total_assets: totalAssets,",
"      total_liabilities: totalLiabilities,",
"      total_equity: totalEquity,",
"      liabilities_plus_equity: totalLiabilities + totalEquity",
"    });",
"  } catch (error) {",
"    console.error('Error generating balance sheet:', error);",
"    res.status(500).json({ error: 'Failed to generate balance sheet' });",
"  }",
"});",
"",
"accountingRouter.get('/accounting/reports/trial-balance', requireAgent, async (req: any, res) => {",
"  // Redirect to the main trial-balance endpoint",
"  try {",
"    const dateCondition = req.query.asAt ? 'AND je.entry_date <= $1' : '';",
"    const params = req.query.asAt ? [req.query.asAt] : [];",
"    const result = await pool.query(",
"      `SELECT coa.id, coa.account_code, coa.account_name, coa.account_type, coa.normal_balance, coa.opening_balance,",
"              COALESCE(SUM(jel.debit_amount), 0) as total_debits,",
"              COALESCE(SUM(jel.credit_amount), 0) as total_credits",
"       FROM chart_of_accounts coa",
"       LEFT JOIN journal_entry_lines jel ON jel.account_id = coa.id",
"       LEFT JOIN journal_entries je ON jel.journal_entry_id = je.id AND je.status = 'posted' ${dateCondition}",
"       WHERE coa.is_active = true",
"       GROUP BY coa.id",
"       ORDER BY coa.account_code`,",
"      params",
"    );",
"    let totalDebitBalances = 0;",
"    let totalCreditBalances = 0;",
"    const accounts = result.rows.map((row: any) => {",
"      const opening = row.opening_balance || 0;",
"      const debits = parseInt(row.total_debits) || 0;",
"      const credits = parseInt(row.total_credits) || 0;",
"      let balance: number;",
"      if (row.normal_balance === 'debit') {",
"        balance = opening + debits - credits;",
"      } else {",
"        balance = opening + credits - debits;",
"      }",
"      if (balance >= 0 && row.normal_balance === 'debit') totalDebitBalances += balance;",
"      else if (balance >= 0 && row.normal_balance === 'credit') totalCreditBalances += balance;",
"      else if (balance < 0 && row.normal_balance === 'debit') totalCreditBalances += Math.abs(balance);",
"      else totalDebitBalances += Math.abs(balance);",
"      return { ...row, total_debits: debits, total_credits: credits, balance };",
"    });",
"    res.json({ accounts, total_debit_balances: totalDebitBalances, total_credit_balances: totalCreditBalances });",
"  } catch (error) {",
"    console.error('Error fetching trial balance report:', error);",
"    res.status(500).json({ error: 'Failed to fetch trial balance report' });",
"  }",
"});",
"",
"accountingRouter.get('/accounting/reports/aged-debtors', requireAgent, async (req: any, res) => {",
"  try {",
"    const result = await pool.query(",
"      `SELECT id, invoice_number, invoice_date, due_date, customer_type, customer_id, customer_name,",
"              total_amount, amount_paid, (total_amount - amount_paid) as outstanding,",
"              EXTRACT(DAY FROM NOW() - due_date) as days_overdue",
"       FROM business_invoices",
"       WHERE status NOT IN ('paid', 'void', 'draft') AND (total_amount - amount_paid) > 0",
"       ORDER BY due_date`",
"    );",
"    // Age into buckets",
"    const buckets = { current: 0, days_1_30: 0, days_31_60: 0, days_61_90: 0, days_90_plus: 0 };",
"    const invoices = result.rows.map((inv: any) => {",
"      const outstanding = parseInt(inv.outstanding) || 0;",
"      const daysOverdue = parseInt(inv.days_overdue) || 0;",
"      let bucket: string;",
"      if (daysOverdue <= 0) { bucket = 'current'; buckets.current += outstanding; }",
"      else if (daysOverdue <= 30) { bucket = '1-30'; buckets.days_1_30 += outstanding; }",
"      else if (daysOverdue <= 60) { bucket = '31-60'; buckets.days_31_60 += outstanding; }",
"      else if (daysOverdue <= 90) { bucket = '61-90'; buckets.days_61_90 += outstanding; }",
"      else { bucket = '90+'; buckets.days_90_plus += outstanding; }",
"      return { ...inv, outstanding, days_overdue: daysOverdue, age_bucket: bucket };",
"    });",
"    const totalOutstanding = Object.values(buckets).reduce((a, b) => a + b, 0);",
"    res.json({ invoices, buckets, total_outstanding: totalOutstanding });",
"  } catch (error) {",
"    console.error('Error generating aged debtors report:', error);",
"    res.status(500).json({ error: 'Failed to generate aged debtors report' });",
"  }",
"});",
"",
"accountingRouter.get('/accounting/reports/aged-creditors', requireAgent, async (req: any, res) => {",
"  try {",
"    const result = await pool.query(",
"      `SELECT id, invoice_number, invoice_date, due_date, supplier_type, supplier_id, supplier_name,",
"              total_amount, amount_paid, (total_amount - amount_paid) as outstanding,",
"              EXTRACT(DAY FROM NOW() - due_date) as days_overdue",
"       FROM purchase_invoices",
"       WHERE status NOT IN ('paid', 'void', 'draft') AND (total_amount - amount_paid) > 0",
"       ORDER BY due_date`",
"    );",
"    const buckets = { current: 0, days_1_30: 0, days_31_60: 0, days_61_90: 0, days_90_plus: 0 };",
"    const invoices = result.rows.map((inv: any) => {",
"      const outstanding = parseInt(inv.outstanding) || 0;",
"      const daysOverdue = parseInt(inv.days_overdue) || 0;",
"      let bucket: string;",
"      if (daysOverdue <= 0) { bucket = 'current'; buckets.current += outstanding; }",
"      else if (daysOverdue <= 30) { bucket = '1-30'; buckets.days_1_30 += outstanding; }",
"      else if (daysOverdue <= 60) { bucket = '31-60'; buckets.days_31_60 += outstanding; }",
"      else if (daysOverdue <= 90) { bucket = '61-90'; buckets.days_61_90 += outstanding; }",
"      else { bucket = '90+'; buckets.days_90_plus += outstanding; }",
"      return { ...inv, outstanding, days_overdue: daysOverdue, age_bucket: bucket };",
"    });",
"    const totalOutstanding = Object.values(buckets).reduce((a, b) => a + b, 0);",
"    res.json({ invoices, buckets, total_outstanding: totalOutstanding });",
"  } catch (error) {",
"    console.error('Error generating aged creditors report:', error);",
"    res.status(500).json({ error: 'Failed to generate aged creditors report' });",
"  }",
"});",
"",
"accountingRouter.get('/accounting/reports/cash-flow', requireAgent, async (req: any, res) => {",
"  try {",
"    const { from, to } = req.query;",
"    if (!from || !to) return res.status(400).json({ error: 'from and to dates are required' });",
"    // Cash received (debits to bank/cash accounts)",
"    const received = await pool.query(",
"      `SELECT coa.account_name, COALESCE(SUM(jel.debit_amount), 0) as total",
"       FROM journal_entry_lines jel",
"       JOIN journal_entries je ON jel.journal_entry_id = je.id",
"       JOIN chart_of_accounts coa ON jel.account_id = coa.id",
"       WHERE je.status = 'posted' AND je.entry_date >= $1 AND je.entry_date <= $2",
"       AND coa.account_code IN ('1000', '1001', '1300')",
"       AND jel.debit_amount > 0",
"       GROUP BY coa.id ORDER BY coa.account_code`,",
"      [from, to]",
"    );",
"    // Cash paid (credits from bank/cash accounts)",
"    const paid = await pool.query(",
"      `SELECT coa.account_name, COALESCE(SUM(jel.credit_amount), 0) as total",
"       FROM journal_entry_lines jel",
"       JOIN journal_entries je ON jel.journal_entry_id = je.id",
"       JOIN chart_of_accounts coa ON jel.account_id = coa.id",
"       WHERE je.status = 'posted' AND je.entry_date >= $1 AND je.entry_date <= $2",
"       AND coa.account_code IN ('1000', '1001', '1300')",
"       AND jel.credit_amount > 0",
"       GROUP BY coa.id ORDER BY coa.account_code`,",
"      [from, to]",
"    );",
"    const totalReceived = received.rows.reduce((sum: number, r: any) => sum + (parseInt(r.total) || 0), 0);",
"    const totalPaid = paid.rows.reduce((sum: number, r: any) => sum + (parseInt(r.total) || 0), 0);",
"    const netCashFlow = totalReceived - totalPaid;",
"    res.json({",
"      period: { from, to },",
"      cash_received: received.rows.map((r: any) => ({ ...r, total: parseInt(r.total) || 0 })),",
"      cash_paid: paid.rows.map((r: any) => ({ ...r, total: parseInt(r.total) || 0 })),",
"      total_received: totalReceived,",
"      total_paid: totalPaid,",
"      net_cash_flow: netCashFlow",
"    });",
"  } catch (error) {",
"    console.error('Error generating cash flow report:', error);",
"    res.status(500).json({ error: 'Failed to generate cash flow report' });",
"  }",
"});",
"",
"accountingRouter.get('/accounting/reports/tax/corporation-tax', requireAgent, async (req: any, res) => {",
"  try {",
"    const { from, to } = req.query;",
"    const year = from && to ? { from, to } : (() => {",
"      const now = new Date();",
"      const yearStart = new Date(now.getFullYear(), 3, 1);",
"      if (now < yearStart) yearStart.setFullYear(yearStart.getFullYear() - 1);",
"      const yearEnd = new Date(yearStart);",
"      yearEnd.setFullYear(yearEnd.getFullYear() + 1);",
"      yearEnd.setDate(yearEnd.getDate() - 1);",
"      return { from: yearStart.toISOString(), to: yearEnd.toISOString() };",
"    })();",
"    const revenue = await pool.query(",
"      `SELECT COALESCE(SUM(jel.credit_amount), 0) - COALESCE(SUM(jel.debit_amount), 0) as total",
"       FROM journal_entry_lines jel",
"       JOIN journal_entries je ON jel.journal_entry_id = je.id",
"       JOIN chart_of_accounts coa ON jel.account_id = coa.id",
"       WHERE je.status = 'posted' AND je.entry_date >= $1 AND je.entry_date <= $2",
"       AND coa.account_type = 'revenue'`,",
"      [year.from, year.to]",
"    );",
"    const expenses = await pool.query(",
"      `SELECT COALESCE(SUM(jel.debit_amount), 0) - COALESCE(SUM(jel.credit_amount), 0) as total",
"       FROM journal_entry_lines jel",
"       JOIN journal_entries je ON jel.journal_entry_id = je.id",
"       JOIN chart_of_accounts coa ON jel.account_id = coa.id",
"       WHERE je.status = 'posted' AND je.entry_date >= $1 AND je.entry_date <= $2",
"       AND coa.account_type = 'expense'`,",
"      [year.from, year.to]",
"    );",
"    const totalRevenue = parseInt(revenue.rows[0].total) || 0;",
"    const totalExpenses = parseInt(expenses.rows[0].total) || 0;",
"    const taxableProfit = Math.max(0, totalRevenue - totalExpenses);",
"    // UK small profits rate 19%, main rate 25% (over 250k)",
"    const rate = taxableProfit > 25000000 ? 0.25 : 0.19;",
"    const estimatedTax = Math.round(taxableProfit * rate);",
"    res.json({",
"      period: year,",
"      total_revenue: totalRevenue,",
"      total_expenses: totalExpenses,",
"      taxable_profit: taxableProfit,",
"      tax_rate: rate,",
"      estimated_corporation_tax: estimatedTax",
"    });",
"  } catch (error) {",
"    console.error('Error generating corporation tax estimate:', error);",
"    res.status(500).json({ error: 'Failed to generate corporation tax estimate' });",
"  }",
"});",
"",
"accountingRouter.get('/accounting/reports/tax/annual-summary', requireAgent, async (req: any, res) => {",
"  try {",
"    const taxYear = parseInt(req.query.year as string) || new Date().getFullYear();",
"    const from = `${taxYear}-04-06`;",
"    const to = `${taxYear + 1}-04-05`;",
"    // Revenue",
"    const revenue = await pool.query(",
"      `SELECT COALESCE(SUM(jel.credit_amount), 0) - COALESCE(SUM(jel.debit_amount), 0) as total",
"       FROM journal_entry_lines jel",
"       JOIN journal_entries je ON jel.journal_entry_id = je.id",
"       JOIN chart_of_accounts coa ON jel.account_id = coa.id",
"       WHERE je.status = 'posted' AND je.entry_date >= $1 AND je.entry_date <= $2 AND coa.account_type = 'revenue'`,",
"      [from, to]",
"    );",
"    // Expenses",
"    const expenses = await pool.query(",
"      `SELECT COALESCE(SUM(jel.debit_amount), 0) - COALESCE(SUM(jel.credit_amount), 0) as total",
"       FROM journal_entry_lines jel",
"       JOIN journal_entries je ON jel.journal_entry_id = je.id",
"       JOIN chart_of_accounts coa ON jel.account_id = coa.id",
"       WHERE je.status = 'posted' AND je.entry_date >= $1 AND je.entry_date <= $2 AND coa.account_type = 'expense'`,",
"      [from, to]",
"    );",
"    // VAT collected and paid",
"    const vatReturns = await pool.query(",
"      `SELECT COALESCE(SUM(box1_vat_due_sales), 0) as vat_collected,",
"              COALESCE(SUM(box4_vat_reclaimed_input), 0) as vat_reclaimed,",
"              COALESCE(SUM(box5_net_vat_due), 0) as net_vat",
"       FROM vat_returns",
"       WHERE period_start >= $1 AND period_end <= $2 AND status IN ('calculated', 'submitted', 'paid')`,",
"      [from, to]",
"    );",
"    // Invoices summary",
"    const salesCount = await pool.query(",
"      `SELECT COUNT(*) as count, COALESCE(SUM(total_amount), 0) as total",
"       FROM business_invoices WHERE invoice_date >= $1 AND invoice_date <= $2 AND status != 'void'`,",
"      [from, to]",
"    );",
"    const purchaseCount = await pool.query(",
"      `SELECT COUNT(*) as count, COALESCE(SUM(total_amount), 0) as total",
"       FROM purchase_invoices WHERE invoice_date >= $1 AND invoice_date <= $2 AND status != 'void'`,",
"      [from, to]",
"    );",
"    res.json({",
"      tax_year: `${taxYear}/${taxYear + 1}`,",
"      period: { from, to },",
"      total_revenue: parseInt(revenue.rows[0].total) || 0,",
"      total_expenses: parseInt(expenses.rows[0].total) || 0,",
"      net_profit: (parseInt(revenue.rows[0].total) || 0) - (parseInt(expenses.rows[0].total) || 0),",
"      vat: {",
"        collected: parseInt(vatReturns.rows[0].vat_collected) || 0,",
"        reclaimed: parseInt(vatReturns.rows[0].vat_reclaimed) || 0,",
"        net: parseInt(vatReturns.rows[0].net_vat) || 0",
"      },",
"      sales_invoices: { count: parseInt(salesCount.rows[0].count) || 0, total: parseInt(salesCount.rows[0].total) || 0 },",
"      purchase_invoices: { count: parseInt(purchaseCount.rows[0].count) || 0, total: parseInt(purchaseCount.rows[0].total) || 0 }",
"    });",
"  } catch (error) {",
"    console.error('Error generating annual tax summary:', error);",
"    res.status(500).json({ error: 'Failed to generate annual tax summary' });",
"  }",
"});",
"",
"accountingRouter.get('/accounting/reports/tax/vat-annual', requireAgent, async (req: any, res) => {",
"  try {",
"    const taxYear = parseInt(req.query.year as string) || new Date().getFullYear();",
"    const from = `${taxYear}-04-01`;",
"    const to = `${taxYear + 1}-03-31`;",
"    const result = await pool.query(",
"      `SELECT id, period_start, period_end, status,",
"              box1_vat_due_sales, box2_vat_due_acquisitions, box3_total_vat_due,",
"              box4_vat_reclaimed_input, box5_net_vat_due, box6_total_sales_ex_vat,",
"              box7_total_purchases_ex_vat, submitted_at",
"       FROM vat_returns",
"       WHERE period_start >= $1 AND period_end <= $2",
"       ORDER BY period_start`,",
"      [from, to]",
"    );",
"    const totals = {",
"      box1: 0, box2: 0, box3: 0, box4: 0, box5: 0, box6: 0, box7: 0",
"    };",
"    result.rows.forEach((r: any) => {",
"      totals.box1 += r.box1_vat_due_sales || 0;",
"      totals.box2 += r.box2_vat_due_acquisitions || 0;",
"      totals.box3 += r.box3_total_vat_due || 0;",
"      totals.box4 += r.box4_vat_reclaimed_input || 0;",
"      totals.box5 += r.box5_net_vat_due || 0;",
"      totals.box6 += r.box6_total_sales_ex_vat || 0;",
"      totals.box7 += r.box7_total_purchases_ex_vat || 0;",
"    });",
"    res.json({",
"      tax_year: `${taxYear}/${taxYear + 1}`,",
"      period: { from, to },",
"      quarters: result.rows,",
"      annual_totals: totals",
"    });",
"  } catch (error) {",
"    console.error('Error generating VAT annual report:', error);",
"    res.status(500).json({ error: 'Failed to generate VAT annual report' });",
"  }",
"});",
"",
].join('\n');

fs.appendFileSync(path, content, 'utf8');
console.log('Part 5 appended');
