const fs = require('fs');
const path = 'C:/Users/ziaa/Dropbox/ZA/DEV/PROJECTS/JB_CRM/server/accountingRoutes.ts';

const content = [
"import { Router } from 'express';",
"import { pool } from './db';",
"",
"export const accountingRouter = Router();",
"",
"// Middleware",
"const requireAgent = (req: any, res: any, next: any) => {",
"  if (!req.user) return res.status(401).json({ error: 'Not authenticated' });",
"  if (req.user.role !== 'admin' && req.user.role !== 'agent') return res.status(403).json({ error: 'Not authorized' });",
"  next();",
"};",
"",
"// Helper for dynamic UPDATE queries",
"function buildUpdateQuery(table: string, fields: Record<string, any>, idValue: any): { sql: string; values: any[] } {",
"  const setClauses: string[] = [];",
"  const values: any[] = [];",
"  let paramIndex = 1;",
"  for (const [key, value] of Object.entries(fields)) {",
'    setClauses.push(`"${key}" = $${paramIndex}`);',
"    values.push(value);",
"    paramIndex++;",
"  }",
'  setClauses.push(`"updated_at" = NOW()`);',
"  values.push(idValue);",
"  const sql = `UPDATE ${table} SET ${setClauses.join(', ')} WHERE id = $${paramIndex} RETURNING *`;",
"  return { sql, values };",
"}",
"",
"// ==========================================",
"// BUSINESS SETTINGS",
"// ==========================================",
"",
"accountingRouter.get('/accounting/business-settings', requireAgent, async (req: any, res) => {",
"  try {",
"    const result = await pool.query('SELECT * FROM business_settings LIMIT 1');",
"    if (result.rows.length === 0) {",
"      const insert = await pool.query('INSERT INTO business_settings DEFAULT VALUES RETURNING *');",
"      return res.json(insert.rows[0]);",
"    }",
"    res.json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error fetching business settings:', error);",
"    res.status(500).json({ error: 'Failed to fetch business settings' });",
"  }",
"});",
"",
"accountingRouter.put('/accounting/business-settings', requireAgent, async (req: any, res) => {",
"  try {",
"    const fields = req.body;",
"    const existing = await pool.query('SELECT id FROM business_settings LIMIT 1');",
"    if (existing.rows.length === 0) {",
"      const cols = Object.keys(fields);",
"      const vals = Object.values(fields);",
'      const placeholders = vals.map((_: any, i: number) => `$${i + 1}`).join(", ");',
"      const result = await pool.query(",
'        `INSERT INTO business_settings (${cols.map((c: string) => `"${c}"`).join(", ")}) VALUES (${placeholders}) RETURNING *`,',
"        vals",
"      );",
"      return res.json(result.rows[0]);",
"    }",
"    const id = existing.rows[0].id;",
"    const { sql, values } = buildUpdateQuery('business_settings', fields, id);",
"    const result = await pool.query(sql, values);",
"    res.json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error updating business settings:', error);",
"    res.status(500).json({ error: 'Failed to update business settings' });",
"  }",
"});",
"",
"// ==========================================",
"// CHART OF ACCOUNTS",
"// ==========================================",
"",
"accountingRouter.get('/accounting/chart-of-accounts', requireAgent, async (req: any, res) => {",
"  try {",
"    const conditions: string[] = [];",
"    const params: any[] = [];",
"    let paramIndex = 1;",
"    if (req.query.type) {",
"      conditions.push(`account_type = $${paramIndex++}`);",
"      params.push(req.query.type);",
"    }",
"    if (req.query.active !== undefined) {",
"      conditions.push(`is_active = $${paramIndex++}`);",
"      params.push(req.query.active === 'true');",
"    }",
"    const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';",
"    const result = await pool.query(",
"      `SELECT * FROM chart_of_accounts ${where} ORDER BY sort_order, account_code`,",
"      params",
"    );",
"    res.json(result.rows);",
"  } catch (error) {",
"    console.error('Error fetching chart of accounts:', error);",
"    res.status(500).json({ error: 'Failed to fetch chart of accounts' });",
"  }",
"});",
"",
"accountingRouter.get('/accounting/chart-of-accounts/:id', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const result = await pool.query('SELECT * FROM chart_of_accounts WHERE id = $1', [id]);",
"    if (result.rows.length === 0) return res.status(404).json({ error: 'Account not found' });",
"    res.json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error fetching account:', error);",
"    res.status(500).json({ error: 'Failed to fetch account' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/chart-of-accounts', requireAgent, async (req: any, res) => {",
"  try {",
"    const { account_code, account_name, account_type, parent_account_id, is_system_account, description, normal_balance, default_tax_rate_id, opening_balance, sort_order } = req.body;",
"    const result = await pool.query(",
"      `INSERT INTO chart_of_accounts (account_code, account_name, account_type, parent_account_id, is_system_account, description, normal_balance, default_tax_rate_id, opening_balance, sort_order)",
"       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING *`,",
"      [account_code, account_name, account_type, parent_account_id || null, is_system_account || false, description || null, normal_balance || null, default_tax_rate_id || null, opening_balance || 0, sort_order || 0]",
"    );",
"    res.status(201).json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error creating account:', error);",
"    res.status(500).json({ error: 'Failed to create account' });",
"  }",
"});",
"",
"accountingRouter.put('/accounting/chart-of-accounts/:id', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const { sql, values } = buildUpdateQuery('chart_of_accounts', req.body, id);",
"    const result = await pool.query(sql, values);",
"    if (result.rows.length === 0) return res.status(404).json({ error: 'Account not found' });",
"    res.json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error updating account:', error);",
"    res.status(500).json({ error: 'Failed to update account' });",
"  }",
"});",
"",
"accountingRouter.delete('/accounting/chart-of-accounts/:id', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const result = await pool.query(",
"      'UPDATE chart_of_accounts SET is_active = false, updated_at = NOW() WHERE id = $1 RETURNING *',",
"      [id]",
"    );",
"    if (result.rows.length === 0) return res.status(404).json({ error: 'Account not found' });",
"    res.json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error deactivating account:', error);",
"    res.status(500).json({ error: 'Failed to deactivate account' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/chart-of-accounts/seed', requireAgent, async (req: any, res) => {",
"  try {",
"    const defaults = [",
"      { code: '1000', name: 'Cash at Bank', type: 'asset', normal: 'debit', sort: 100, system: true },",
"      { code: '1001', name: 'Petty Cash', type: 'asset', normal: 'debit', sort: 101, system: true },",
"      { code: '1100', name: 'Accounts Receivable', type: 'asset', normal: 'debit', sort: 110, system: true },",
"      { code: '1200', name: 'Prepayments', type: 'asset', normal: 'debit', sort: 120, system: false },",
"      { code: '1300', name: 'Client Money Account', type: 'asset', normal: 'debit', sort: 130, system: true },",
"      { code: '1500', name: 'Fixed Assets', type: 'asset', normal: 'debit', sort: 150, system: false },",
"      { code: '1510', name: 'Accumulated Depreciation', type: 'asset', normal: 'credit', sort: 151, system: false },",
"      { code: '2000', name: 'Accounts Payable', type: 'liability', normal: 'credit', sort: 200, system: true },",
"      { code: '2100', name: 'VAT Payable', type: 'liability', normal: 'credit', sort: 210, system: true },",
"      { code: '2110', name: 'VAT Receivable', type: 'asset', normal: 'debit', sort: 211, system: true },",
"      { code: '2200', name: 'PAYE/NI Payable', type: 'liability', normal: 'credit', sort: 220, system: false },",
"      { code: '2300', name: 'Corporation Tax Payable', type: 'liability', normal: 'credit', sort: 230, system: false },",
"      { code: '2400', name: 'Client Deposits Held', type: 'liability', normal: 'credit', sort: 240, system: true },",
"      { code: '2500', name: 'Landlord Funds Held', type: 'liability', normal: 'credit', sort: 250, system: true },",
"      { code: '3000', name: 'Share Capital', type: 'equity', normal: 'credit', sort: 300, system: true },",
"      { code: '3100', name: 'Retained Earnings', type: 'equity', normal: 'credit', sort: 310, system: true },",
"      { code: '3200', name: 'Dividends', type: 'equity', normal: 'debit', sort: 320, system: false },",
"      { code: '4000', name: 'Management Fee Income', type: 'revenue', normal: 'credit', sort: 400, system: false },",
"      { code: '4010', name: 'Letting Fee Income', type: 'revenue', normal: 'credit', sort: 401, system: false },",
"      { code: '4020', name: 'Sales Commission Income', type: 'revenue', normal: 'credit', sort: 402, system: false },",
"      { code: '4030', name: 'Renewal Fee Income', type: 'revenue', normal: 'credit', sort: 403, system: false },",
"      { code: '4040', name: 'Inventory Fee Income', type: 'revenue', normal: 'credit', sort: 404, system: false },",
"      { code: '4050', name: 'Administration Fee Income', type: 'revenue', normal: 'credit', sort: 405, system: false },",
"      { code: '4100', name: 'Other Income', type: 'revenue', normal: 'credit', sort: 410, system: false },",
"      { code: '5000', name: 'Staff Costs', type: 'expense', normal: 'debit', sort: 500, system: false },",
"      { code: '5010', name: 'Employer NI', type: 'expense', normal: 'debit', sort: 501, system: false },",
"      { code: '5020', name: 'Pension Contributions', type: 'expense', normal: 'debit', sort: 502, system: false },",
"      { code: '6000', name: 'Office Rent', type: 'expense', normal: 'debit', sort: 600, system: false },",
"      { code: '6010', name: 'Office Utilities', type: 'expense', normal: 'debit', sort: 601, system: false },",
"      { code: '6020', name: 'Office Insurance', type: 'expense', normal: 'debit', sort: 602, system: false },",
"      { code: '6100', name: 'Marketing & Advertising', type: 'expense', normal: 'debit', sort: 610, system: false },",
"      { code: '6110', name: 'Portal Listings', type: 'expense', normal: 'debit', sort: 611, system: false },",
"      { code: '6200', name: 'Software & Subscriptions', type: 'expense', normal: 'debit', sort: 620, system: false },",
"      { code: '6300', name: 'Professional Fees', type: 'expense', normal: 'debit', sort: 630, system: false },",
"      { code: '6400', name: 'Travel & Motor', type: 'expense', normal: 'debit', sort: 640, system: false },",
"      { code: '6500', name: 'Telephone & Internet', type: 'expense', normal: 'debit', sort: 650, system: false },",
"      { code: '6600', name: 'Depreciation', type: 'expense', normal: 'debit', sort: 660, system: false },",
"      { code: '6700', name: 'Bank Charges', type: 'expense', normal: 'debit', sort: 670, system: false },",
"      { code: '6800', name: 'Sundry Expenses', type: 'expense', normal: 'debit', sort: 680, system: false },",
"      { code: '6900', name: 'Contractor Costs', type: 'expense', normal: 'debit', sort: 690, system: false },",
"    ];",
"    let seeded = 0;",
"    for (const acc of defaults) {",
"      const exists = await pool.query('SELECT id FROM chart_of_accounts WHERE account_code = $1', [acc.code]);",
"      if (exists.rows.length === 0) {",
"        await pool.query(",
"          `INSERT INTO chart_of_accounts (account_code, account_name, account_type, normal_balance, sort_order, is_system_account)",
"           VALUES ($1, $2, $3, $4, $5, $6)`,",
"          [acc.code, acc.name, acc.type, acc.normal, acc.sort, acc.system]",
"        );",
"        seeded++;",
"      }",
"    }",
"    res.json({ message: `Seeded ${seeded} accounts (${defaults.length - seeded} already existed)` });",
"  } catch (error) {",
"    console.error('Error seeding accounts:', error);",
"    res.status(500).json({ error: 'Failed to seed accounts' });",
"  }",
"});",
"",
"accountingRouter.get('/accounting/chart-of-accounts/:id/balance', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const account = await pool.query('SELECT * FROM chart_of_accounts WHERE id = $1', [id]);",
"    if (account.rows.length === 0) return res.status(404).json({ error: 'Account not found' });",
"    const result = await pool.query(",
"      `SELECT COALESCE(SUM(jel.debit_amount), 0) as total_debits,",
"              COALESCE(SUM(jel.credit_amount), 0) as total_credits",
"       FROM journal_entry_lines jel",
"       JOIN journal_entries je ON jel.journal_entry_id = je.id",
"       WHERE jel.account_id = $1 AND je.status = 'posted'`,",
"      [id]",
"    );",
"    const { total_debits, total_credits } = result.rows[0];",
"    const openingBalance = account.rows[0].opening_balance || 0;",
"    const normalBalance = account.rows[0].normal_balance;",
"    let balance: number;",
"    if (normalBalance === 'debit') {",
"      balance = openingBalance + parseInt(total_debits) - parseInt(total_credits);",
"    } else {",
"      balance = openingBalance + parseInt(total_credits) - parseInt(total_debits);",
"    }",
"    res.json({ account_id: parseInt(id), opening_balance: openingBalance, total_debits: parseInt(total_debits), total_credits: parseInt(total_credits), balance });",
"  } catch (error) {",
"    console.error('Error fetching account balance:', error);",
"    res.status(500).json({ error: 'Failed to fetch account balance' });",
"  }",
"});",
"",
"// ==========================================",
"// TAX RATES",
"// ==========================================",
"",
"accountingRouter.get('/accounting/tax-rates', requireAgent, async (req: any, res) => {",
"  try {",
"    const result = await pool.query('SELECT * FROM tax_rates ORDER BY name');",
"    res.json(result.rows);",
"  } catch (error) {",
"    console.error('Error fetching tax rates:', error);",
"    res.status(500).json({ error: 'Failed to fetch tax rates' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/tax-rates', requireAgent, async (req: any, res) => {",
"  try {",
"    const { name, rate, tax_type, is_default, description, effective_from, effective_to } = req.body;",
"    const result = await pool.query(",
"      `INSERT INTO tax_rates (name, rate, tax_type, is_default, description, effective_from, effective_to)",
"       VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING *`,",
"      [name, rate, tax_type || null, is_default || false, description || null, effective_from || null, effective_to || null]",
"    );",
"    res.status(201).json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error creating tax rate:', error);",
"    res.status(500).json({ error: 'Failed to create tax rate' });",
"  }",
"});",
"",
"accountingRouter.put('/accounting/tax-rates/:id', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const { sql, values } = buildUpdateQuery('tax_rates', req.body, id);",
"    const result = await pool.query(sql, values);",
"    if (result.rows.length === 0) return res.status(404).json({ error: 'Tax rate not found' });",
"    res.json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error updating tax rate:', error);",
"    res.status(500).json({ error: 'Failed to update tax rate' });",
"  }",
"});",
"",
"accountingRouter.delete('/accounting/tax-rates/:id', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const result = await pool.query(",
"      'UPDATE tax_rates SET is_active = false, updated_at = NOW() WHERE id = $1 RETURNING *',",
"      [id]",
"    );",
"    if (result.rows.length === 0) return res.status(404).json({ error: 'Tax rate not found' });",
"    res.json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error deactivating tax rate:', error);",
"    res.status(500).json({ error: 'Failed to deactivate tax rate' });",
"  }",
"});",
].join('\n');

fs.writeFileSync(path, content, 'utf8');
console.log('Part 1 written, length:', content.length);
