const fs = require('fs');
const path = 'C:/Users/ziaa/Dropbox/ZA/DEV/PROJECTS/JB_CRM/server/accountingRoutes.ts';

const content = [
"",
"// ==========================================",
"// CREDIT NOTES",
"// ==========================================",
"",
"accountingRouter.get('/accounting/credit-notes', requireAgent, async (req: any, res) => {",
"  try {",
"    const conditions: string[] = [];",
"    const params: any[] = [];",
"    let paramIndex = 1;",
"    if (req.query.status) {",
"      conditions.push(`status = $${paramIndex++}`);",
"      params.push(req.query.status);",
"    }",
"    if (req.query.customerId) {",
"      conditions.push(`customer_id = $${paramIndex++}`);",
"      params.push(parseInt(req.query.customerId));",
"    }",
"    const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';",
"    const result = await pool.query(",
"      `SELECT * FROM credit_notes ${where} ORDER BY credit_note_date DESC`,",
"      params",
"    );",
"    res.json(result.rows);",
"  } catch (error) {",
"    console.error('Error fetching credit notes:', error);",
"    res.status(500).json({ error: 'Failed to fetch credit notes' });",
"  }",
"});",
"",
"accountingRouter.get('/accounting/credit-notes/:id', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const result = await pool.query('SELECT * FROM credit_notes WHERE id = $1', [id]);",
"    if (result.rows.length === 0) return res.status(404).json({ error: 'Credit note not found' });",
"    res.json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error fetching credit note:', error);",
"    res.status(500).json({ error: 'Failed to fetch credit note' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/credit-notes', requireAgent, async (req: any, res) => {",
"  const client = await pool.connect();",
"  try {",
"    await client.query('BEGIN');",
"    const body = req.body;",
"    const settings = await client.query('SELECT credit_note_prefix, credit_note_next_number FROM business_settings LIMIT 1');",
"    let prefix = 'JBCN';",
"    let nextNum = 1;",
"    if (settings.rows.length > 0) {",
"      prefix = settings.rows[0].credit_note_prefix || 'JBCN';",
"      nextNum = settings.rows[0].credit_note_next_number || 1;",
"    }",
"    const creditNoteNumber = body.credit_note_number || `${prefix}-${String(nextNum).padStart(5, '0')}`;",
"    const result = await client.query(",
"      `INSERT INTO credit_notes (credit_note_number, credit_note_date, original_invoice_id, customer_type, customer_id, customer_name, subtotal, vat_amount, total_amount, status, reason, notes, created_by_id)",
"       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13) RETURNING *`,",
"      [creditNoteNumber, body.credit_note_date, body.original_invoice_id || null, body.customer_type || null, body.customer_id || null, body.customer_name, body.subtotal || 0, body.vat_amount || 0, body.total_amount || 0, body.status || 'draft', body.reason || null, body.notes || null, req.user?.id || null]",
"    );",
"    if (settings.rows.length > 0) {",
"      await client.query('UPDATE business_settings SET credit_note_next_number = credit_note_next_number + 1');",
"    }",
"    await client.query('COMMIT');",
"    res.status(201).json(result.rows[0]);",
"  } catch (error) {",
"    await client.query('ROLLBACK');",
"    console.error('Error creating credit note:', error);",
"    res.status(500).json({ error: 'Failed to create credit note' });",
"  } finally {",
"    client.release();",
"  }",
"});",
"",
"accountingRouter.post('/accounting/credit-notes/:id/apply', requireAgent, async (req: any, res) => {",
"  const client = await pool.connect();",
"  try {",
"    await client.query('BEGIN');",
"    const { id } = req.params;",
"    const { invoice_id, amount } = req.body;",
"    const cn = await client.query('SELECT * FROM credit_notes WHERE id = $1', [id]);",
"    if (cn.rows.length === 0) {",
"      await client.query('ROLLBACK');",
"      return res.status(404).json({ error: 'Credit note not found' });",
"    }",
"    const creditNote = cn.rows[0];",
"    const remaining = creditNote.total_amount - (creditNote.amount_applied || 0);",
"    if (amount > remaining) {",
"      await client.query('ROLLBACK');",
"      return res.status(400).json({ error: `Amount exceeds remaining credit (${remaining} pence available)` });",
"    }",
"    const newApplied = (creditNote.amount_applied || 0) + amount;",
"    const cnStatus = newApplied >= creditNote.total_amount ? 'fully_applied' : 'partially_applied';",
"    await client.query(",
"      'UPDATE credit_notes SET amount_applied = $2, status = $3, updated_at = NOW() WHERE id = $1',",
"      [id, newApplied, cnStatus]",
"    );",
"    // Reduce invoice balance",
"    const inv = await client.query('SELECT * FROM business_invoices WHERE id = $1', [invoice_id]);",
"    if (inv.rows.length > 0) {",
"      const newPaid = (inv.rows[0].amount_paid || 0) + amount;",
"      const invStatus = newPaid >= inv.rows[0].total_amount ? 'paid' : 'partially_paid';",
"      await client.query(",
"        `UPDATE business_invoices SET amount_paid = $2, status = $3, updated_at = NOW() WHERE id = $1`,",
"        [invoice_id, newPaid, invStatus]",
"      );",
"    }",
"    // Create allocation record",
"    await client.query(",
"      `INSERT INTO payment_allocations (payment_date, amount, payment_method, allocation_type, allocation_id, notes, created_by_id)",
"       VALUES (NOW(), $1, 'credit_note', 'credit_note', $2, $3, $4)`,",
"      [amount, id, `Applied to invoice #${invoice_id}`, req.user?.id || null]",
"    );",
"    await client.query('COMMIT');",
"    const updated = await pool.query('SELECT * FROM credit_notes WHERE id = $1', [id]);",
"    res.json(updated.rows[0]);",
"  } catch (error) {",
"    await client.query('ROLLBACK');",
"    console.error('Error applying credit note:', error);",
"    res.status(500).json({ error: 'Failed to apply credit note' });",
"  } finally {",
"    client.release();",
"  }",
"});",
"",
"// ==========================================",
"// PAYMENT ALLOCATIONS",
"// ==========================================",
"",
"accountingRouter.get('/accounting/payment-allocations', requireAgent, async (req: any, res) => {",
"  try {",
"    const conditions: string[] = [];",
"    const params: any[] = [];",
"    let paramIndex = 1;",
"    if (req.query.type) {",
"      conditions.push(`allocation_type = $${paramIndex++}`);",
"      params.push(req.query.type);",
"    }",
"    if (req.query.id) {",
"      conditions.push(`allocation_id = $${paramIndex++}`);",
"      params.push(parseInt(req.query.id));",
"    }",
"    const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';",
"    const result = await pool.query(",
"      `SELECT * FROM payment_allocations ${where} ORDER BY payment_date DESC`,",
"      params",
"    );",
"    res.json(result.rows);",
"  } catch (error) {",
"    console.error('Error fetching payment allocations:', error);",
"    res.status(500).json({ error: 'Failed to fetch payment allocations' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/payment-allocations', requireAgent, async (req: any, res) => {",
"  try {",
"    const { payment_date, amount, payment_method, payment_reference, allocation_type, allocation_id, bank_account_id, notes } = req.body;",
"    const result = await pool.query(",
"      `INSERT INTO payment_allocations (payment_date, amount, payment_method, payment_reference, allocation_type, allocation_id, bank_account_id, notes, created_by_id)",
"       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING *`,",
"      [payment_date, amount, payment_method || null, payment_reference || null, allocation_type || null, allocation_id || null, bank_account_id || null, notes || null, req.user?.id || null]",
"    );",
"    res.status(201).json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error creating payment allocation:', error);",
"    res.status(500).json({ error: 'Failed to create payment allocation' });",
"  }",
"});",
"",
"accountingRouter.get('/accounting/unallocated-payments', requireAgent, async (req: any, res) => {",
"  try {",
"    const result = await pool.query(",
"      `SELECT * FROM payment_allocations WHERE allocation_type IS NULL OR allocation_id IS NULL ORDER BY payment_date DESC`",
"    );",
"    res.json(result.rows);",
"  } catch (error) {",
"    console.error('Error fetching unallocated payments:', error);",
"    res.status(500).json({ error: 'Failed to fetch unallocated payments' });",
"  }",
"});",
"",
"// ==========================================",
"// RECURRING TEMPLATES",
"// ==========================================",
"",
"accountingRouter.get('/accounting/recurring-templates', requireAgent, async (req: any, res) => {",
"  try {",
"    const result = await pool.query('SELECT * FROM recurring_invoice_templates ORDER BY template_name');",
"    res.json(result.rows);",
"  } catch (error) {",
"    console.error('Error fetching recurring templates:', error);",
"    res.status(500).json({ error: 'Failed to fetch recurring templates' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/recurring-templates', requireAgent, async (req: any, res) => {",
"  try {",
"    const b = req.body;",
"    const result = await pool.query(",
"      `INSERT INTO recurring_invoice_templates (template_name, customer_type, customer_id, customer_name, frequency, day_of_month, line_items, subtotal, vat_amount, total_amount, property_id, account_id, tax_rate_id, next_generation_date, notes, created_by_id)",
"       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16) RETURNING *`,",
"      [b.template_name, b.customer_type || null, b.customer_id || null, b.customer_name, b.frequency, b.day_of_month || null, JSON.stringify(b.line_items || []), b.subtotal || 0, b.vat_amount || 0, b.total_amount || 0, b.property_id || null, b.account_id || null, b.tax_rate_id || null, b.next_generation_date || null, b.notes || null, req.user?.id || null]",
"    );",
"    res.status(201).json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error creating recurring template:', error);",
"    res.status(500).json({ error: 'Failed to create recurring template' });",
"  }",
"});",
"",
"accountingRouter.put('/accounting/recurring-templates/:id', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const fields = { ...req.body };",
"    if (fields.line_items) fields.line_items = JSON.stringify(fields.line_items);",
"    const { sql, values } = buildUpdateQuery('recurring_invoice_templates', fields, id);",
"    const result = await pool.query(sql, values);",
"    if (result.rows.length === 0) return res.status(404).json({ error: 'Template not found' });",
"    res.json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error updating recurring template:', error);",
"    res.status(500).json({ error: 'Failed to update recurring template' });",
"  }",
"});",
"",
"accountingRouter.delete('/accounting/recurring-templates/:id', requireAgent, async (req: any, res) => {",
"  try {",
"    const { id } = req.params;",
"    const result = await pool.query(",
"      'UPDATE recurring_invoice_templates SET is_active = false, updated_at = NOW() WHERE id = $1 RETURNING *',",
"      [id]",
"    );",
"    if (result.rows.length === 0) return res.status(404).json({ error: 'Template not found' });",
"    res.json(result.rows[0]);",
"  } catch (error) {",
"    console.error('Error deactivating recurring template:', error);",
"    res.status(500).json({ error: 'Failed to deactivate recurring template' });",
"  }",
"});",
"",
"accountingRouter.post('/accounting/recurring-templates/:id/run', requireAgent, async (req: any, res) => {",
"  const client = await pool.connect();",
"  try {",
"    await client.query('BEGIN');",
"    const { id } = req.params;",
"    const tmpl = await client.query('SELECT * FROM recurring_invoice_templates WHERE id = $1 AND is_active = true', [id]);",
"    if (tmpl.rows.length === 0) {",
"      await client.query('ROLLBACK');",
"      return res.status(404).json({ error: 'Active template not found' });",
"    }",
"    const t = tmpl.rows[0];",
"    const settings = await client.query('SELECT sales_invoice_prefix, sales_invoice_next_number FROM business_settings LIMIT 1');",
"    let prefix = 'JBINV';",
"    let nextNum = 1;",
"    if (settings.rows.length > 0) {",
"      prefix = settings.rows[0].sales_invoice_prefix || 'JBINV';",
"      nextNum = settings.rows[0].sales_invoice_next_number || 1;",
"    }",
"    const invoiceNumber = `${prefix}-${String(nextNum).padStart(5, '0')}`;",
"    const now = new Date();",
"    const dueDate = new Date(now);",
"    dueDate.setDate(dueDate.getDate() + 30);",
"    const invoiceResult = await client.query(",
"      `INSERT INTO business_invoices (invoice_number, invoice_date, due_date, customer_type, customer_id, customer_name, subtotal, vat_amount, total_amount, status, property_id, notes, created_by_id)",
"       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'draft', $10, $11, $12) RETURNING *`,",
"      [invoiceNumber, now.toISOString(), dueDate.toISOString(), t.customer_type, t.customer_id, t.customer_name, t.subtotal || 0, t.vat_amount || 0, t.total_amount || 0, t.property_id, `Generated from template: ${t.template_name}`, req.user?.id || null]",
"    );",
"    const invoiceId = invoiceResult.rows[0].id;",
"    const lineItems = typeof t.line_items === 'string' ? JSON.parse(t.line_items) : (t.line_items || []);",
"    for (let i = 0; i < lineItems.length; i++) {",
"      const line = lineItems[i];",
"      await client.query(",
"        `INSERT INTO business_invoice_lines (business_invoice_id, description, quantity, unit_price, line_total, tax_rate_id, tax_amount, account_id, sort_order)",
"         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,",
"        [invoiceId, line.description, line.quantity || 1, line.unit_price || 0, line.line_total || 0, line.tax_rate_id || null, line.tax_amount || 0, line.account_id || t.account_id || null, i]",
"      );",
"    }",
"    // Update template tracking",
"    let nextGenDate = null;",
"    if (t.frequency === 'weekly') { nextGenDate = new Date(now); nextGenDate.setDate(nextGenDate.getDate() + 7); }",
"    else if (t.frequency === 'monthly') { nextGenDate = new Date(now); nextGenDate.setMonth(nextGenDate.getMonth() + 1); }",
"    else if (t.frequency === 'quarterly') { nextGenDate = new Date(now); nextGenDate.setMonth(nextGenDate.getMonth() + 3); }",
"    else if (t.frequency === 'annually') { nextGenDate = new Date(now); nextGenDate.setFullYear(nextGenDate.getFullYear() + 1); }",
"    await client.query(",
"      'UPDATE recurring_invoice_templates SET last_generated_date = NOW(), next_generation_date = $2, updated_at = NOW() WHERE id = $1',",
"      [id, nextGenDate ? nextGenDate.toISOString() : null]",
"    );",
"    if (settings.rows.length > 0) {",
"      await client.query('UPDATE business_settings SET sales_invoice_next_number = sales_invoice_next_number + 1');",
"    }",
"    await client.query('COMMIT');",
"    res.status(201).json(invoiceResult.rows[0]);",
"  } catch (error) {",
"    await client.query('ROLLBACK');",
"    console.error('Error running recurring template:', error);",
"    res.status(500).json({ error: 'Failed to generate invoice from template' });",
"  } finally {",
"    client.release();",
"  }",
"});",
].join('\n');

fs.appendFileSync(path, content, 'utf8');
console.log('Part 4 appended');
