-- Performance Indexes for Accounting System
CREATE INDEX IF NOT EXISTS idx_coa_account_type ON chart_of_accounts(account_type);
CREATE INDEX IF NOT EXISTS idx_coa_parent ON chart_of_accounts(parent_account_id);
CREATE INDEX IF NOT EXISTS idx_coa_active ON chart_of_accounts(is_active);
CREATE INDEX IF NOT EXISTS idx_tax_rates_type ON tax_rates(tax_type);
CREATE INDEX IF NOT EXISTS idx_tax_rates_active ON tax_rates(is_active);
CREATE INDEX IF NOT EXISTS idx_financial_periods_status ON financial_periods(status);
CREATE INDEX IF NOT EXISTS idx_financial_periods_dates ON financial_periods(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_financial_periods_year ON financial_periods(financial_year);
CREATE INDEX IF NOT EXISTS idx_je_entry_date ON journal_entries(entry_date);
CREATE INDEX IF NOT EXISTS idx_je_status ON journal_entries(status);
CREATE INDEX IF NOT EXISTS idx_je_source ON journal_entries(source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_je_period ON journal_entries(financial_period_id);
CREATE INDEX IF NOT EXISTS idx_jel_journal ON journal_entry_lines(journal_entry_id);
CREATE INDEX IF NOT EXISTS idx_jel_account ON journal_entry_lines(account_id);
CREATE INDEX IF NOT EXISTS idx_jel_property ON journal_entry_lines(property_id);
CREATE INDEX IF NOT EXISTS idx_jel_landlord ON journal_entry_lines(landlord_id);
CREATE INDEX IF NOT EXISTS idx_jel_tenant ON journal_entry_lines(tenant_id);
CREATE INDEX IF NOT EXISTS idx_jel_tax_rate ON journal_entry_lines(tax_rate_id);
CREATE INDEX IF NOT EXISTS idx_bi_status ON business_invoices(status);
CREATE INDEX IF NOT EXISTS idx_bi_customer ON business_invoices(customer_type, customer_id);
CREATE INDEX IF NOT EXISTS idx_bi_due_date ON business_invoices(due_date);
CREATE INDEX IF NOT EXISTS idx_bi_invoice_date ON business_invoices(invoice_date);
CREATE INDEX IF NOT EXISTS idx_bi_property ON business_invoices(property_id);
CREATE INDEX IF NOT EXISTS idx_bil_invoice ON business_invoice_lines(business_invoice_id);
CREATE INDEX IF NOT EXISTS idx_pi_status ON purchase_invoices(status);
CREATE INDEX IF NOT EXISTS idx_pi_supplier ON purchase_invoices(supplier_type, supplier_id);
CREATE INDEX IF NOT EXISTS idx_pi_due_date ON purchase_invoices(due_date);
CREATE INDEX IF NOT EXISTS idx_pi_property ON purchase_invoices(property_id);
CREATE INDEX IF NOT EXISTS idx_pi_landlord ON purchase_invoices(landlord_id);
CREATE INDEX IF NOT EXISTS idx_pil_invoice ON purchase_invoice_lines(purchase_invoice_id);
CREATE INDEX IF NOT EXISTS idx_cn_status ON credit_notes(status);
CREATE INDEX IF NOT EXISTS idx_cn_original ON credit_notes(original_invoice_id);
CREATE INDEX IF NOT EXISTS idx_pa_type ON payment_allocations(allocation_type, allocation_id);
CREATE INDEX IF NOT EXISTS idx_pa_date ON payment_allocations(payment_date);
CREATE INDEX IF NOT EXISTS idx_vr_period ON vat_returns(period_start, period_end);
CREATE INDEX IF NOT EXISTS idx_vr_status ON vat_returns(status);
CREATE INDEX IF NOT EXISTS idx_vrt_return ON vat_return_transactions(vat_return_id);
CREATE INDEX IF NOT EXISTS idx_rit_active ON recurring_invoice_templates(is_active);
CREATE INDEX IF NOT EXISTS idx_rit_next_date ON recurring_invoice_templates(next_generation_date);
